### ISSUE TITLE
cmake-roll cleans all repomd including Rocks-6.2

### ISSUE THREAD

**Issue by jhladysz** [sdsc/cmake-roll#1]
Please help. cmake-roll created, added, enabled  and then after having created new rocks distro the roll was run. The result:
# rocks run roll cmake |bash  and I saw:

Cleaning repos: 
Cleaning up Everything
Setting up Install Process
Nothing to do
Setting up Install Process
Nothing to do
Setting up Install Process
Nothing to do
I'm in trouble as I cannot use yum. The question is **How to revert** I don't have Rocks-6.2 repomd.xml nor gpg key etc. Please help.
Jerzy
PS. roll tested with result:
# ./cmake.t

ok 1 - cmake installed
not ok 2 - cmake-generated build
# Failed test 'cmake-generated build'
# at ./cmake.t line 58.
# 'init.c(556):ERROR:161: Cannot initialize TCL
# tmpcmake.sh: line 7: cmake: command not found
# make: **\* No rule to make target `hello.exe'.  Stop.
# tmpcmake.sh: line 9: ./hello.exe: No such file or directory
# '
# doesn't match '(?-xism:world)'

ok 3 - cmake module installed
ok 4 - cmake version module installed
ok 5 - cmake version module link created
1..5
# Looks like you failed 1 test of 5.

So, there is a trouble but no use of the roll.

**Comment by jjhayes** [comment]
That's an odd error.  What output do you get from

```
module avail cmake
```

The cmake roll does nothing but install three rpm packages, so uninstalling it should require only

```
rpm -e sdsc-cmake{,-modules,-roll-test}
```

Jim

**Comment by jhladysz** [comment]
Hello Jim,
 
I need help in retrieving /var/cache/yum repository data which vanished, cleaned. My frontend cannot update anymore.
I especialy need the data concerning Rocks-6.2 repository data. Can you please tell where to find
these rpms. Or can you send me your /var/cache/yum data (with or without cached packages)?
 
Cmake was a requirement for hdf-roll, hdf-roll was a requirement for netcdf-roll, and the latter
was required for vmd-roll, and so on. Now I do not despair for cmake. I only want my frontend to be
functional again.
 
 
Will you please help,
Jerzy
PS.[root@stork ~]# module avail cmake
init.c(556):ERROR:161: Cannot initialize TCL
and nothing more
[root@stork ~]# rpm -qa | grep cmake
sdsc-cmake-roll-test-1-1.x86_64
sdsc-cmake-3.3.2-0.x86_64
sdsc-cmake-modules-3.3.2-2.x86_64

**Comment by jjhayes** [comment]
Sounds like the distro rebuild might have failed because your / partition filled.  Does the output of

```
df -h /
```

show it to be 100% used?  I'd suggest running

```
rocks remove roll cmake clean=y
```

then rebuilding your distro.

Jim

**Comment by jhladysz** [comment]
Hi Jim,
This is my df -h :
[root@stork ~]# df -h /
Filesystem      
Size  Used Avail Use% Mounted on/dev/sda2       
115G   33G   77G  30% /
Now I have:
/var/cache/yum/base retrieved
/var/cache/yum/centosplus retrieved
/var/cache/yum/elrepo retrieved
/var/cache/yum/epel retrieved
/var/cache/yum/softwarecollections retrieved
but
/var/cache/yum/Rocks-6-2  empty
/var/cache/yum/lammps-icms empty
/var/cache/yum/cuda-7-5-local empty
 
Thank you Jim for your help. 
But, how about retrieving /var/cache/yum/Rocks-6-2 ?

## I consider it the most important.

Jerzy

**Comment by jjhayes** [comment]
I'm not familiar with details of the yum cache operation.  The page

```
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/sec-Working_with_Yum_Cache.html
```

gives an overview that might be helpful.  If yum isn't working, then it sounds like the contents of /etc/yum.repos.d might be an issue.  If that looks okay, then I'd try rebuilding the Rocks distro if you haven't already.

Jim

**Comment by jhladysz** [comment]
Hello Jim,
I'd like to thank you very much, but it is always "yes,thank you".
I have some news. Cmake-roll is ok. The origin of the error and a great trouble for me
was: anaconda2 installed as application in usual place. The problem with anaconda2 is such that if I
configure PATH and LD_LIBRARY_PATH variables to use it :::: I cannot use modules any more until I close the bash shell.
But I placed it in /etc/bashrc and all instances of bash used it. I was the reason for fail of testing the roll.
bashrc introduced another tcl on the path so Tool Command Language used in modules was not working.
I eliminated anaconda2 from searching path and modules work, tests of cmake prooved it is healthy.
 
The problem with yum repo for Rocks-6.2 remained.
But I have another problem with Rocks. It's completely my foult
I issued a command of creating new distro and then rocks run roll |bash not giving the name of the roll.
Is it necessary to reinstall the cluster now? Now Rocks does not see any rolls.
Does Rocks remember previous distro, and I could come back to previous one?
How can I make my Rocks cluster healthy again?
I know, it is far beyond the cmake roll topic, but if you'd be so kind to help?
Greetings,
Jerzy

**Comment by jjhayes** [comment]
The TCL explanation makes sense.  We've seen occasions before where a different TCL installation in the user's path has caused failures.

I had no idea that "rocks install roll" without specifying a roll name would attempt a full install.  Unfortunately, I would guess that the partial reinstall has left your system in an unstable state and so a fresh installation is your only safe option.

Jim

**Comment by jhladysz** [comment]
Thank you very much for your kind help.
The mysql database could not close ?nodes?, I can't remember what exactly was not closed, but it was something related to mysql database.Recently, I was able to login to mysql database through client software. The items are in unclosed state. As I have no knowledge of mysql I didn't touch it. But perhaps there is a way to make the database healthy? I asked such question at mailing list npaci-rocks and StackOverflow. However, I have no answers so far.
Thank you once more,
Jerzy

**Comment by tcooper** [comment]
Issue is not with cmake-roll, per-se, and discussion moved to Rocks Mailing List.
